project:
  type: website
  output-dir: docs

website:
  title: "Nursing the Numbers"
  navbar:
    right:
      - text: "About me" 
        href: https://louieneri.github.io/
      - icon: twitter
        href: https://twitter.com/louieneri_ 
      - icon: linkedin
        href: https://www.linkedin.com/in/louie-neri/
      - icon: github
        href: https://github.com/louieneri 
        
format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: darkly
    styles: styles.css

editor: visual

