project:
  type: website
  output-dir: docs

website:
  title: "Nursing the Numbers"
  navbar:
    right:
      - text: "About me" 
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    styles: styles.css

editor: visual

